weights: yolov5m.pt
cfg: ''
data: ../datasets/full_teeth/full_teeth.yaml
hyp:
  lr0: 0.001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.3
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.5
  translate: 0.1
  scale: 0.9
  shear: 0.5
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.5
  copy_paste: 0.5
epochs: 500
batch_size: 16
imgsz: 800
rect: true
resume: false
nosave: false
noval: false
noautoanchor: true
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: true
optimizer: Adam
sync_bn: false
workers: 8
project: ../models
name: full_teeth_single_class
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: ../models/full_teeth_single_class
